// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/masterseed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // how many derived seeds caller wants
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeedsRequest) Reset() {
	*x = GetSeedsRequest{}
	mi := &file_proto_masterseed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedsRequest) ProtoMessage() {}

func (x *GetSeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterseed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedsRequest.ProtoReflect.Descriptor instead.
func (*GetSeedsRequest) Descriptor() ([]byte, []int) {
	return file_proto_masterseed_proto_rawDescGZIP(), []int{0}
}

func (x *GetSeedsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetSeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeedsResponse) Reset() {
	*x = GetSeedsResponse{}
	mi := &file_proto_masterseed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedsResponse) ProtoMessage() {}

func (x *GetSeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_masterseed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedsResponse.ProtoReflect.Descriptor instead.
func (*GetSeedsResponse) Descriptor() ([]byte, []int) {
	return file_proto_masterseed_proto_rawDescGZIP(), []int{1}
}

func (x *GetSeedsResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_masterseed_proto protoreflect.FileDescriptor

const file_proto_masterseed_proto_rawDesc = "" +
	"\n" +
	"\x16proto/masterseed.proto\x12\n" +
	"masterseed\"'\n" +
	"\x0fGetSeedsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"*\n" +
	"\x10GetSeedsResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2Y\n" +
	"\x10MasterSeedPlugin\x12E\n" +
	"\bGetSeeds\x12\x1b.masterseed.GetSeedsRequest\x1a\x1c.masterseed.GetSeedsResponseB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_masterseed_proto_rawDescOnce sync.Once
	file_proto_masterseed_proto_rawDescData []byte
)

func file_proto_masterseed_proto_rawDescGZIP() []byte {
	file_proto_masterseed_proto_rawDescOnce.Do(func() {
		file_proto_masterseed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_masterseed_proto_rawDesc), len(file_proto_masterseed_proto_rawDesc)))
	})
	return file_proto_masterseed_proto_rawDescData
}

var file_proto_masterseed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_masterseed_proto_goTypes = []any{
	(*GetSeedsRequest)(nil),  // 0: masterseed.GetSeedsRequest
	(*GetSeedsResponse)(nil), // 1: masterseed.GetSeedsResponse
}
var file_proto_masterseed_proto_depIdxs = []int32{
	0, // 0: masterseed.MasterSeedPlugin.GetSeeds:input_type -> masterseed.GetSeedsRequest
	1, // 1: masterseed.MasterSeedPlugin.GetSeeds:output_type -> masterseed.GetSeedsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_masterseed_proto_init() }
func file_proto_masterseed_proto_init() {
	if File_proto_masterseed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_masterseed_proto_rawDesc), len(file_proto_masterseed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_masterseed_proto_goTypes,
		DependencyIndexes: file_proto_masterseed_proto_depIdxs,
		MessageInfos:      file_proto_masterseed_proto_msgTypes,
	}.Build()
	File_proto_masterseed_proto = out.File
	file_proto_masterseed_proto_goTypes = nil
	file_proto_masterseed_proto_depIdxs = nil
}
