// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/masterseed.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterSeedPlugin_GetSeeds_FullMethodName = "/masterseed.MasterSeedPlugin/GetSeeds"
)

// MasterSeedPluginClient is the client API for MasterSeedPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterSeedPluginClient interface {
	GetSeeds(ctx context.Context, in *GetSeedsRequest, opts ...grpc.CallOption) (*GetSeedsResponse, error)
}

type masterSeedPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterSeedPluginClient(cc grpc.ClientConnInterface) MasterSeedPluginClient {
	return &masterSeedPluginClient{cc}
}

func (c *masterSeedPluginClient) GetSeeds(ctx context.Context, in *GetSeedsRequest, opts ...grpc.CallOption) (*GetSeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeedsResponse)
	err := c.cc.Invoke(ctx, MasterSeedPlugin_GetSeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterSeedPluginServer is the server API for MasterSeedPlugin service.
// All implementations must embed UnimplementedMasterSeedPluginServer
// for forward compatibility.
type MasterSeedPluginServer interface {
	GetSeeds(context.Context, *GetSeedsRequest) (*GetSeedsResponse, error)
	mustEmbedUnimplementedMasterSeedPluginServer()
}

// UnimplementedMasterSeedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterSeedPluginServer struct{}

func (UnimplementedMasterSeedPluginServer) GetSeeds(context.Context, *GetSeedsRequest) (*GetSeedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeeds not implemented")
}
func (UnimplementedMasterSeedPluginServer) mustEmbedUnimplementedMasterSeedPluginServer() {}
func (UnimplementedMasterSeedPluginServer) testEmbeddedByValue()                          {}

// UnsafeMasterSeedPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterSeedPluginServer will
// result in compilation errors.
type UnsafeMasterSeedPluginServer interface {
	mustEmbedUnimplementedMasterSeedPluginServer()
}

func RegisterMasterSeedPluginServer(s grpc.ServiceRegistrar, srv MasterSeedPluginServer) {
	// If the following call pancis, it indicates UnimplementedMasterSeedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterSeedPlugin_ServiceDesc, srv)
}

func _MasterSeedPlugin_GetSeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterSeedPluginServer).GetSeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterSeedPlugin_GetSeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterSeedPluginServer).GetSeeds(ctx, req.(*GetSeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterSeedPlugin_ServiceDesc is the grpc.ServiceDesc for MasterSeedPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterSeedPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "masterseed.MasterSeedPlugin",
	HandlerType: (*MasterSeedPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeeds",
			Handler:    _MasterSeedPlugin_GetSeeds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/masterseed.proto",
}
