// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/trng.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomnessPlugin_GetTrng_FullMethodName = "/trng.RandomnessPlugin/GetTrng"
)

// RandomnessPluginClient is the client API for RandomnessPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomnessPluginClient interface {
	GetTrng(ctx context.Context, in *TrngRequest, opts ...grpc.CallOption) (*TrngResponse, error)
}

type randomnessPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomnessPluginClient(cc grpc.ClientConnInterface) RandomnessPluginClient {
	return &randomnessPluginClient{cc}
}

func (c *randomnessPluginClient) GetTrng(ctx context.Context, in *TrngRequest, opts ...grpc.CallOption) (*TrngResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrngResponse)
	err := c.cc.Invoke(ctx, RandomnessPlugin_GetTrng_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomnessPluginServer is the server API for RandomnessPlugin service.
// All implementations must embed UnimplementedRandomnessPluginServer
// for forward compatibility.
type RandomnessPluginServer interface {
	GetTrng(context.Context, *TrngRequest) (*TrngResponse, error)
	mustEmbedUnimplementedRandomnessPluginServer()
}

// UnimplementedRandomnessPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomnessPluginServer struct{}

func (UnimplementedRandomnessPluginServer) GetTrng(context.Context, *TrngRequest) (*TrngResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrng not implemented")
}
func (UnimplementedRandomnessPluginServer) mustEmbedUnimplementedRandomnessPluginServer() {}
func (UnimplementedRandomnessPluginServer) testEmbeddedByValue()                          {}

// UnsafeRandomnessPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomnessPluginServer will
// result in compilation errors.
type UnsafeRandomnessPluginServer interface {
	mustEmbedUnimplementedRandomnessPluginServer()
}

func RegisterRandomnessPluginServer(s grpc.ServiceRegistrar, srv RandomnessPluginServer) {
	// If the following call panics, it indicates UnimplementedRandomnessPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomnessPlugin_ServiceDesc, srv)
}

func _RandomnessPlugin_GetTrng_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrngRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomnessPluginServer).GetTrng(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomnessPlugin_GetTrng_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomnessPluginServer).GetTrng(ctx, req.(*TrngRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomnessPlugin_ServiceDesc is the grpc.ServiceDesc for RandomnessPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomnessPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trng.RandomnessPlugin",
	HandlerType: (*RandomnessPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrng",
			Handler:    _RandomnessPlugin_GetTrng_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trng.proto",
}
