x-plugin-base:
  &plugin-base
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/metrics"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s

x-mocker-base:
  &mocker-base
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  plugin-ipfs:
    <<: *plugin-base
    container_name: plugin-ipfs
    build:
      context: ./plugins
    image: op-plugin:latest
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=ipfs
      - ORBITPORT_GRPC_PORT=50002
      - ORBITPORT_IPFS_ADDRESS=http://ipfs-node:5001
    ports:
      - 50002:50002 # expose the port for integration tests

  aptos-orbital-api:
    <<: *mocker-base
    container_name: aptos-orbital-api
    build:
      context: ./plugins
      args:
        - BUILD_TARGET=mocker
    image: op-mocker:latest
    environment:
      - OPMOCK_SERVICE=aptosorbital_api
      - OPMOCK_PORT=8001
      - OPMOCK_PROFILE=${OPMOCK_PROFILE}
    depends_on:
      - aptos-orbital-auth

  aptos-orbital-auth:
    <<: *mocker-base
    container_name: aptos-orbital-auth
    build:
      context: ./plugins
      args:
        - BUILD_TARGET=mocker
    image: op-mocker:latest
    environment:
      - OPMOCK_SERVICE=aptosorbital_auth
      - OPMOCK_PORT=8002
    ports:
      - "8002:8002"

  plugin-aptos-orbital:
    <<: *plugin-base
    container_name: plugin-aptos-orbital
    build:
      context: ./plugins
    image: op-plugin:latest
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=aptosorbital
      - ORBITPORT_GRPC_PORT=50001
      - ORBITPORT_APTOS_ORBITAL_CLIENT_ID=2e4c704ae4d059e1
      - ORBITPORT_APTOS_ORBITAL_CLIENT_SECRET=2e4c704ae4d059e1
      - ORBITPORT_APTOS_ORBITAL_API_URL=http://aptos-orbital-api:8001
      - ORBITPORT_APTOS_ORBITAL_AUTH_URL=http://aptos-orbital-auth:8002
      - ORBITPORT_APTOS_ORBITAL_DEFAULT_MASTER_SEED=288ae5323d7a34ada0fb29962cfdc9d5ce4bb2bcdb4b0f137a464d9bd6ceb982
      - ORBITPORT_APTOS_ORBITAL_TRNG_SIZE=32
      - ORBITPORT_APTOS_ORBITAL_MAX_MASTER_SEEDS=10
      - ORBITPORT_APTOS_ORBITAL_SEED_PERIOD=3600
    depends_on:
      - plugin-auth
      - aptos-orbital-api
      - aptos-orbital-auth

  plugin-auth:
    <<: *plugin-base
    container_name: plugin-auth
    build:
      context: ./plugins
    image: op-plugin:latest
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=auth
      - ORBITPORT_GRPC_PORT=50000
      # - ORBITPORT_AUTH0_DOMAIN=${ORBITPORT_AUTH0_DOMAIN}
      # - ORBITPORT_AUTH0_AUDIENCE=${ORBITPORT_AUTH0_AUDIENCE}

  ipfs-node:
    image: ipfs/kubo:release
    ports:
      - "4001:4001"  # IPFS Swarm Port
      - "5001:5001"  # IPFS API Port
      - "8081:8080"  # IPFS Gateway Port
    volumes:
      - ./.data/ipfs_dev:/data/ipfs
    command: ["daemon", "--migrate=true", "--offline"]

  gateway:
    container_name: gateway 
    image: op-gateway:latest
    build:
      context: ./gateway
    environment:
      - RUST_LOG=warn,gateway=debug
      - ORBITPORT_HTTP_PORT=8080
      - ORBITPORT_AUTH_PLUGIN=http://plugin-auth:50000
      - ORBITPORT_TRNG_PLUGIN=http://plugin-aptos-orbital:50001
      - ORBITPORT_DEFAULT_MASTER_SEED=${ORBITPORT_DEFAULT_MASTER_SEED}
    ports:
      - 8080:8080

  plugin-beacon:
    <<: *plugin-base
    container_name: plugin-beacon
    build:
      context: ./plugins
    image: op-plugin:latest
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=beacon
      - ORBITPORT_IPFS_PLUGIN=plugin-ipfs:50002
      - ORBITPORT_CTRNG_PLUGIN=plugin-aptos-orbital:50001
