x-plugin-base:
  &plugin-base
  image: op-plugin:latest
  build:
    context: ./plugins
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/metrics"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s

services:
  plugin-ipfs:
    <<: *plugin-base
    container_name: plugin-ipfs
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=ipfs
      - ORBITPORT_GRPC_PORT=50002
      - ORBITPORT_IPFS_ADDRESS=http://ipfs-node:5001

  plugin-aptos-orbital:
    <<: *plugin-base
    container_name: plugin-aptos-orbital
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=aptosorbital
      - ORBITPORT_GRPC_PORT=50001
      - ORBITPORT_APTOS_ORBITAL_CLIENT_ID=${ORBITPORT_APTOS_ORBITAL_CLIENT_ID}
      - ORBITPORT_APTOS_ORBITAL_CLIENT_SECRET=${ORBITPORT_APTOS_ORBITAL_CLIENT_SECRET}

  plugin-auth:
    <<: *plugin-base
    container_name: plugin-auth
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=auth
      - ORBITPORT_GRPC_PORT=50000
      - ORBITPORT_AUTH0_DOMAIN=${ORBITPORT_AUTH0_DOMAIN}
      - ORBITPORT_AUTH0_AUDIENCE=${ORBITPORT_AUTH0_AUDIENCE}

  ipfs-node:
    image: ipfs/kubo:release
    container_name: ipfs-node
    ports:
      - "4001:4001"  # IPFS Swarm Port
      - "5001:5001"  # IPFS API Port
      - "8081:8080"  # IPFS Gateway Port
    volumes:
      - ${ORBITPORT_IPFS_DATA_DIR}:/data/ipfs
    command: ["daemon", "--migrate=true"]

  gateway:
    container_name: gateway 
    image: op-gateway:latest
    build:
      context: ./gateway
    environment:
      - RUST_LOG=warn,orbitport=debug
      - ORBITPORT_HTTP_PORT=8080
      - ORBITPORT_AUTH_PLUGIN=http://plugin-auth:50000
      - ORBITPORT_TRNG_PLUGIN=http://plugin-aptos-orbital:50001
    depends_on:
      - plugin-aptos-orbital
      - plugin-auth
    ports:
      - 8080:8080

  plugin-beacon:
    <<: *plugin-base
    container_name: plugin-beacon
    build:
      context: ./plugins
    image: op-plugin:latest
    environment:
      - GOLOG_LOG_LEVEL=debug
      - ORBITPORT_PLUGIN=beacon
      - ORBITPORT_IPFS_PLUGIN=plugin-ipfs:50002
      - ORBITPORT_CTRNG_PLUGIN=plugin-aptos-orbital:50001