// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthAgent_ValidateToken_FullMethodName = "/auth.AuthAgent/ValidateToken"
)

// AuthAgentClient is the client API for AuthAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthAgentClient interface {
	ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error)
}

type authAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthAgentClient(cc grpc.ClientConnInterface) AuthAgentClient {
	return &authAgentClient{cc}
}

func (c *authAgentClient) ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenValidationResponse)
	err := c.cc.Invoke(ctx, AuthAgent_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthAgentServer is the server API for AuthAgent service.
// All implementations must embed UnimplementedAuthAgentServer
// for forward compatibility.
type AuthAgentServer interface {
	ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error)
	mustEmbedUnimplementedAuthAgentServer()
}

// UnimplementedAuthAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthAgentServer struct{}

func (UnimplementedAuthAgentServer) ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthAgentServer) mustEmbedUnimplementedAuthAgentServer() {}
func (UnimplementedAuthAgentServer) testEmbeddedByValue()                   {}

// UnsafeAuthAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthAgentServer will
// result in compilation errors.
type UnsafeAuthAgentServer interface {
	mustEmbedUnimplementedAuthAgentServer()
}

func RegisterAuthAgentServer(s grpc.ServiceRegistrar, srv AuthAgentServer) {
	// If the following call pancis, it indicates UnimplementedAuthAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthAgent_ServiceDesc, srv)
}

func _AuthAgent_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAgentServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAgent_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAgentServer).ValidateToken(ctx, req.(*TokenValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthAgent_ServiceDesc is the grpc.ServiceDesc for AuthAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthAgent",
	HandlerType: (*AuthAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthAgent_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
