// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/ipfs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IpnsName      *string                `protobuf:"bytes,2,opt,name=ipns_name,json=ipnsName,proto3,oneof" json:"ipns_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_ipfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddRequest) GetIpnsName() string {
	if x != nil && x.IpnsName != nil {
		return *x.IpnsName
	}
	return ""
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	IpnsName      *string                `protobuf:"bytes,2,opt,name=ipns_name,json=ipnsName,proto3,oneof" json:"ipns_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_ipfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AddResponse) GetIpnsName() string {
	if x != nil && x.IpnsName != nil {
		return *x.IpnsName
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ipfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_ipfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_ipfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ipfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipfs_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ipfs_proto protoreflect.FileDescriptor

const file_proto_ipfs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/ipfs.proto\x12\x04ipfs\"P\n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12 \n" +
	"\tipns_name\x18\x02 \x01(\tH\x00R\bipnsName\x88\x01\x01B\f\n" +
	"\n" +
	"_ipns_name\"O\n" +
	"\vAddResponse\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12 \n" +
	"\tipns_name\x18\x02 \x01(\tH\x00R\bipnsName\x88\x01\x01B\f\n" +
	"\n" +
	"_ipns_name\"<\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"!\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9f\x01\n" +
	"\x10IpfsAgentService\x12*\n" +
	"\x03Add\x12\x10.ipfs.AddRequest\x1a\x11.ipfs.AddResponse\x12*\n" +
	"\x03Get\x12\x10.ipfs.GetRequest\x1a\x11.ipfs.GetResponse\x123\n" +
	"\x06Delete\x12\x13.ipfs.DeleteRequest\x1a\x14.ipfs.DeleteResponseB0Z.github.com/spacecoinxyz/orbitport/agents/protob\x06proto3"

var (
	file_proto_ipfs_proto_rawDescOnce sync.Once
	file_proto_ipfs_proto_rawDescData []byte
)

func file_proto_ipfs_proto_rawDescGZIP() []byte {
	file_proto_ipfs_proto_rawDescOnce.Do(func() {
		file_proto_ipfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ipfs_proto_rawDesc), len(file_proto_ipfs_proto_rawDesc)))
	})
	return file_proto_ipfs_proto_rawDescData
}

var file_proto_ipfs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ipfs_proto_goTypes = []any{
	(*AddRequest)(nil),     // 0: ipfs.AddRequest
	(*AddResponse)(nil),    // 1: ipfs.AddResponse
	(*GetRequest)(nil),     // 2: ipfs.GetRequest
	(*GetResponse)(nil),    // 3: ipfs.GetResponse
	(*DeleteRequest)(nil),  // 4: ipfs.DeleteRequest
	(*DeleteResponse)(nil), // 5: ipfs.DeleteResponse
}
var file_proto_ipfs_proto_depIdxs = []int32{
	0, // 0: ipfs.IpfsAgentService.Add:input_type -> ipfs.AddRequest
	2, // 1: ipfs.IpfsAgentService.Get:input_type -> ipfs.GetRequest
	4, // 2: ipfs.IpfsAgentService.Delete:input_type -> ipfs.DeleteRequest
	1, // 3: ipfs.IpfsAgentService.Add:output_type -> ipfs.AddResponse
	3, // 4: ipfs.IpfsAgentService.Get:output_type -> ipfs.GetResponse
	5, // 5: ipfs.IpfsAgentService.Delete:output_type -> ipfs.DeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ipfs_proto_init() }
func file_proto_ipfs_proto_init() {
	if File_proto_ipfs_proto != nil {
		return
	}
	file_proto_ipfs_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_ipfs_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ipfs_proto_rawDesc), len(file_proto_ipfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ipfs_proto_goTypes,
		DependencyIndexes: file_proto_ipfs_proto_depIdxs,
		MessageInfos:      file_proto_ipfs_proto_msgTypes,
	}.Build()
	File_proto_ipfs_proto = out.File
	file_proto_ipfs_proto_goTypes = nil
	file_proto_ipfs_proto_depIdxs = nil
}
