// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/trng.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrngRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IgnoreSig     bool                   `protobuf:"varint,1,opt,name=ignore_sig,json=ignoreSig,proto3" json:"ignore_sig,omitempty"`
	Chunks        uint32                 `protobuf:"varint,2,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrngRequest) Reset() {
	*x = TrngRequest{}
	mi := &file_proto_trng_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrngRequest) ProtoMessage() {}

func (x *TrngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trng_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrngRequest.ProtoReflect.Descriptor instead.
func (*TrngRequest) Descriptor() ([]byte, []int) {
	return file_proto_trng_proto_rawDescGZIP(), []int{0}
}

func (x *TrngRequest) GetIgnoreSig() bool {
	if x != nil {
		return x.IgnoreSig
	}
	return false
}

func (x *TrngRequest) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

type TrngResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sig           string                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrngResponse) Reset() {
	*x = TrngResponse{}
	mi := &file_proto_trng_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrngResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrngResponse) ProtoMessage() {}

func (x *TrngResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trng_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrngResponse.ProtoReflect.Descriptor instead.
func (*TrngResponse) Descriptor() ([]byte, []int) {
	return file_proto_trng_proto_rawDescGZIP(), []int{1}
}

func (x *TrngResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TrngResponse) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

var File_proto_trng_proto protoreflect.FileDescriptor

const file_proto_trng_proto_rawDesc = "" +
	"\n" +
	"\x10proto/trng.proto\x12\x04trng\"D\n" +
	"\vTrngRequest\x12\x1d\n" +
	"\n" +
	"ignore_sig\x18\x01 \x01(\bR\tignoreSig\x12\x16\n" +
	"\x06chunks\x18\x02 \x01(\rR\x06chunks\"6\n" +
	"\fTrngResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\tR\x03sig2C\n" +
	"\x0fRandomnessAgent\x120\n" +
	"\aGetTrng\x12\x11.trng.TrngRequest\x1a\x12.trng.TrngResponseB0Z.github.com/spacecoinxyz/orbitport/agents/protob\x06proto3"

var (
	file_proto_trng_proto_rawDescOnce sync.Once
	file_proto_trng_proto_rawDescData []byte
)

func file_proto_trng_proto_rawDescGZIP() []byte {
	file_proto_trng_proto_rawDescOnce.Do(func() {
		file_proto_trng_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trng_proto_rawDesc), len(file_proto_trng_proto_rawDesc)))
	})
	return file_proto_trng_proto_rawDescData
}

var file_proto_trng_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trng_proto_goTypes = []any{
	(*TrngRequest)(nil),  // 0: trng.TrngRequest
	(*TrngResponse)(nil), // 1: trng.TrngResponse
}
var file_proto_trng_proto_depIdxs = []int32{
	0, // 0: trng.RandomnessAgent.GetTrng:input_type -> trng.TrngRequest
	1, // 1: trng.RandomnessAgent.GetTrng:output_type -> trng.TrngResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trng_proto_init() }
func file_proto_trng_proto_init() {
	if File_proto_trng_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trng_proto_rawDesc), len(file_proto_trng_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trng_proto_goTypes,
		DependencyIndexes: file_proto_trng_proto_depIdxs,
		MessageInfos:      file_proto_trng_proto_msgTypes,
	}.Build()
	File_proto_trng_proto = out.File
	file_proto_trng_proto_goTypes = nil
	file_proto_trng_proto_depIdxs = nil
}
