// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/trng.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomnessAgent_GetTrng_FullMethodName = "/trng.RandomnessAgent/GetTrng"
)

// RandomnessAgentClient is the client API for RandomnessAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomnessAgentClient interface {
	GetTrng(ctx context.Context, in *TrngRequest, opts ...grpc.CallOption) (*TrngResponse, error)
}

type randomnessAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomnessAgentClient(cc grpc.ClientConnInterface) RandomnessAgentClient {
	return &randomnessAgentClient{cc}
}

func (c *randomnessAgentClient) GetTrng(ctx context.Context, in *TrngRequest, opts ...grpc.CallOption) (*TrngResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrngResponse)
	err := c.cc.Invoke(ctx, RandomnessAgent_GetTrng_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomnessAgentServer is the server API for RandomnessAgent service.
// All implementations must embed UnimplementedRandomnessAgentServer
// for forward compatibility.
type RandomnessAgentServer interface {
	GetTrng(context.Context, *TrngRequest) (*TrngResponse, error)
	mustEmbedUnimplementedRandomnessAgentServer()
}

// UnimplementedRandomnessAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomnessAgentServer struct{}

func (UnimplementedRandomnessAgentServer) GetTrng(context.Context, *TrngRequest) (*TrngResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrng not implemented")
}
func (UnimplementedRandomnessAgentServer) mustEmbedUnimplementedRandomnessAgentServer() {}
func (UnimplementedRandomnessAgentServer) testEmbeddedByValue()                         {}

// UnsafeRandomnessAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomnessAgentServer will
// result in compilation errors.
type UnsafeRandomnessAgentServer interface {
	mustEmbedUnimplementedRandomnessAgentServer()
}

func RegisterRandomnessAgentServer(s grpc.ServiceRegistrar, srv RandomnessAgentServer) {
	// If the following call pancis, it indicates UnimplementedRandomnessAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomnessAgent_ServiceDesc, srv)
}

func _RandomnessAgent_GetTrng_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrngRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomnessAgentServer).GetTrng(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomnessAgent_GetTrng_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomnessAgentServer).GetTrng(ctx, req.(*TrngRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomnessAgent_ServiceDesc is the grpc.ServiceDesc for RandomnessAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomnessAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trng.RandomnessAgent",
	HandlerType: (*RandomnessAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrng",
			Handler:    _RandomnessAgent_GetTrng_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/trng.proto",
}
