// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/plugins/account.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HoldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Auth0 client_id from the validated JWT's sub claim.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Compute units consumed by this request. MVP: always 1.
	Units uint32 `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	// Operation tag for ledger description + metrics ("trng", "kms_sign", ...).
	Operation     string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_proto_plugins_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{0}
}

func (x *HoldRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HoldRequest) GetUnits() uint32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *HoldRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type HoldResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the dashboard accepted the hold.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// CreditLedger row ID. Pass back to Release on downstream failure.
	LedgerId string `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	// Account's balance after the hold. Surfaced in metrics, not headers.
	BalanceAfter int64 `protobuf:"varint,3,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	// Reserved for future ok=false signaling. Currently the plugin returns a
	// non-nil gRPC status (FailedPrecondition / Unavailable) instead of a
	// response with ok=false, so callers should branch on the gRPC error code.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_proto_plugins_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{1}
}

func (x *HoldResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HoldResponse) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *HoldResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *HoldResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerId      string                 `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_proto_plugins_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{2}
}

func (x *SettleRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_proto_plugins_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{3}
}

func (x *SettleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SettleResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *SettleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerId      string                 `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_plugins_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_proto_plugins_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_account_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReleaseResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *ReleaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_plugins_account_proto protoreflect.FileDescriptor

const file_proto_plugins_account_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/plugins/account.proto\x12\aaccount\"^\n" +
	"\vHoldRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05units\x18\x02 \x01(\rR\x05units\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"v\n" +
	"\fHoldResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12#\n" +
	"\rbalance_after\x18\x03 \x01(\x03R\fbalanceAfter\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\",\n" +
	"\rSettleRequest\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\tR\bledgerId\"[\n" +
	"\x0eSettleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x03R\fbalanceAfter\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\x0eReleaseRequest\x12\x1b\n" +
	"\tledger_id\x18\x01 \x01(\tR\bledgerId\"\\\n" +
	"\x0fReleaseResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x03R\fbalanceAfter\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xbd\x01\n" +
	"\rAccountPlugin\x123\n" +
	"\x04Hold\x12\x14.account.HoldRequest\x1a\x15.account.HoldResponse\x129\n" +
	"\x06Settle\x12\x16.account.SettleRequest\x1a\x17.account.SettleResponse\x12<\n" +
	"\aRelease\x12\x17.account.ReleaseRequest\x1a\x18.account.ReleaseResponseB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_plugins_account_proto_rawDescOnce sync.Once
	file_proto_plugins_account_proto_rawDescData []byte
)

func file_proto_plugins_account_proto_rawDescGZIP() []byte {
	file_proto_plugins_account_proto_rawDescOnce.Do(func() {
		file_proto_plugins_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugins_account_proto_rawDesc), len(file_proto_plugins_account_proto_rawDesc)))
	})
	return file_proto_plugins_account_proto_rawDescData
}

var file_proto_plugins_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_plugins_account_proto_goTypes = []any{
	(*HoldRequest)(nil),     // 0: account.HoldRequest
	(*HoldResponse)(nil),    // 1: account.HoldResponse
	(*SettleRequest)(nil),   // 2: account.SettleRequest
	(*SettleResponse)(nil),  // 3: account.SettleResponse
	(*ReleaseRequest)(nil),  // 4: account.ReleaseRequest
	(*ReleaseResponse)(nil), // 5: account.ReleaseResponse
}
var file_proto_plugins_account_proto_depIdxs = []int32{
	0, // 0: account.AccountPlugin.Hold:input_type -> account.HoldRequest
	2, // 1: account.AccountPlugin.Settle:input_type -> account.SettleRequest
	4, // 2: account.AccountPlugin.Release:input_type -> account.ReleaseRequest
	1, // 3: account.AccountPlugin.Hold:output_type -> account.HoldResponse
	3, // 4: account.AccountPlugin.Settle:output_type -> account.SettleResponse
	5, // 5: account.AccountPlugin.Release:output_type -> account.ReleaseResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_plugins_account_proto_init() }
func file_proto_plugins_account_proto_init() {
	if File_proto_plugins_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugins_account_proto_rawDesc), len(file_proto_plugins_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugins_account_proto_goTypes,
		DependencyIndexes: file_proto_plugins_account_proto_depIdxs,
		MessageInfos:      file_proto_plugins_account_proto_msgTypes,
	}.Build()
	File_proto_plugins_account_proto = out.File
	file_proto_plugins_account_proto_goTypes = nil
	file_proto_plugins_account_proto_depIdxs = nil
}
