// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/plugins/account.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountPlugin_Hold_FullMethodName    = "/account.AccountPlugin/Hold"
	AccountPlugin_Settle_FullMethodName  = "/account.AccountPlugin/Settle"
	AccountPlugin_Release_FullMethodName = "/account.AccountPlugin/Release"
)

// AccountPluginClient is the client API for AccountPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountPlugin gates JWT-authenticated requests by holding credits
// against the dashboard backend account service before the gateway
// dispatches the request to its downstream plugins.
type AccountPluginClient interface {
	// Hold deducts credits atomically against the Account owning client_id.
	// The dashboard returns a ledger_id the gateway uses to settle on success
	// or release on failure.
	Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error)
	// Settle commits a previous hold: it marks the ledger row resolved so the
	// dashboard sweeper no longer treats it as an orphan to refund. Balance is
	// unchanged (the hold already deducted). Idempotent — duplicate calls are
	// no-ops. The gateway calls this once the downstream request succeeds.
	Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error)
	// Release refunds a previous hold. Idempotent — duplicate calls are no-ops.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type accountPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountPluginClient(cc grpc.ClientConnInterface) AccountPluginClient {
	return &accountPluginClient{cc}
}

func (c *accountPluginClient) Hold(ctx context.Context, in *HoldRequest, opts ...grpc.CallOption) (*HoldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldResponse)
	err := c.cc.Invoke(ctx, AccountPlugin_Hold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountPluginClient) Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleResponse)
	err := c.cc.Invoke(ctx, AccountPlugin_Settle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountPluginClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, AccountPlugin_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountPluginServer is the server API for AccountPlugin service.
// All implementations must embed UnimplementedAccountPluginServer
// for forward compatibility.
//
// AccountPlugin gates JWT-authenticated requests by holding credits
// against the dashboard backend account service before the gateway
// dispatches the request to its downstream plugins.
type AccountPluginServer interface {
	// Hold deducts credits atomically against the Account owning client_id.
	// The dashboard returns a ledger_id the gateway uses to settle on success
	// or release on failure.
	Hold(context.Context, *HoldRequest) (*HoldResponse, error)
	// Settle commits a previous hold: it marks the ledger row resolved so the
	// dashboard sweeper no longer treats it as an orphan to refund. Balance is
	// unchanged (the hold already deducted). Idempotent — duplicate calls are
	// no-ops. The gateway calls this once the downstream request succeeds.
	Settle(context.Context, *SettleRequest) (*SettleResponse, error)
	// Release refunds a previous hold. Idempotent — duplicate calls are no-ops.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedAccountPluginServer()
}

// UnimplementedAccountPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountPluginServer struct{}

func (UnimplementedAccountPluginServer) Hold(context.Context, *HoldRequest) (*HoldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hold not implemented")
}
func (UnimplementedAccountPluginServer) Settle(context.Context, *SettleRequest) (*SettleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settle not implemented")
}
func (UnimplementedAccountPluginServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedAccountPluginServer) mustEmbedUnimplementedAccountPluginServer() {}
func (UnimplementedAccountPluginServer) testEmbeddedByValue()                       {}

// UnsafeAccountPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountPluginServer will
// result in compilation errors.
type UnsafeAccountPluginServer interface {
	mustEmbedUnimplementedAccountPluginServer()
}

func RegisterAccountPluginServer(s grpc.ServiceRegistrar, srv AccountPluginServer) {
	// If the following call panics, it indicates UnimplementedAccountPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountPlugin_ServiceDesc, srv)
}

func _AccountPlugin_Hold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountPluginServer).Hold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountPlugin_Hold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountPluginServer).Hold(ctx, req.(*HoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountPlugin_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountPluginServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountPlugin_Settle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountPluginServer).Settle(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountPlugin_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountPluginServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountPlugin_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountPluginServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountPlugin_ServiceDesc is the grpc.ServiceDesc for AccountPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountPlugin",
	HandlerType: (*AccountPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hold",
			Handler:    _AccountPlugin_Hold_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _AccountPlugin_Settle_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _AccountPlugin_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/account.proto",
}
