// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/plugins/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPlugin_ValidateToken_FullMethodName        = "/auth.AuthPlugin/ValidateToken"
	AuthPlugin_ValidateServiceToken_FullMethodName = "/auth.AuthPlugin/ValidateServiceToken"
)

// AuthPluginClient is the client API for AuthPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPluginClient interface {
	ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error)
	ValidateServiceToken(ctx context.Context, in *ServiceTokenValidationRequest, opts ...grpc.CallOption) (*ServiceTokenValidationResponse, error)
}

type authPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginClient(cc grpc.ClientConnInterface) AuthPluginClient {
	return &authPluginClient{cc}
}

func (c *authPluginClient) ValidateToken(ctx context.Context, in *TokenValidationRequest, opts ...grpc.CallOption) (*TokenValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenValidationResponse)
	err := c.cc.Invoke(ctx, AuthPlugin_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) ValidateServiceToken(ctx context.Context, in *ServiceTokenValidationRequest, opts ...grpc.CallOption) (*ServiceTokenValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceTokenValidationResponse)
	err := c.cc.Invoke(ctx, AuthPlugin_ValidateServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServer is the server API for AuthPlugin service.
// All implementations must embed UnimplementedAuthPluginServer
// for forward compatibility.
type AuthPluginServer interface {
	ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error)
	ValidateServiceToken(context.Context, *ServiceTokenValidationRequest) (*ServiceTokenValidationResponse, error)
	mustEmbedUnimplementedAuthPluginServer()
}

// UnimplementedAuthPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServer struct{}

func (UnimplementedAuthPluginServer) ValidateToken(context.Context, *TokenValidationRequest) (*TokenValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthPluginServer) ValidateServiceToken(context.Context, *ServiceTokenValidationRequest) (*ServiceTokenValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateServiceToken not implemented")
}
func (UnimplementedAuthPluginServer) mustEmbedUnimplementedAuthPluginServer() {}
func (UnimplementedAuthPluginServer) testEmbeddedByValue()                    {}

// UnsafeAuthPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServer will
// result in compilation errors.
type UnsafeAuthPluginServer interface {
	mustEmbedUnimplementedAuthPluginServer()
}

func RegisterAuthPluginServer(s grpc.ServiceRegistrar, srv AuthPluginServer) {
	// If the following call panics, it indicates UnimplementedAuthPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPlugin_ServiceDesc, srv)
}

func _AuthPlugin_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).ValidateToken(ctx, req.(*TokenValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_ValidateServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceTokenValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).ValidateServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_ValidateServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).ValidateServiceToken(ctx, req.(*ServiceTokenValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPlugin_ServiceDesc is the grpc.ServiceDesc for AuthPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthPlugin",
	HandlerType: (*AuthPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthPlugin_ValidateToken_Handler,
		},
		{
			MethodName: "ValidateServiceToken",
			Handler:    _AuthPlugin_ValidateServiceToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/auth.proto",
}
