// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/plugins/ipfs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpfsPlugin_Add_FullMethodName     = "/ipfs.IpfsPlugin/Add"
	IpfsPlugin_Get_FullMethodName     = "/ipfs.IpfsPlugin/Get"
	IpfsPlugin_Publish_FullMethodName = "/ipfs.IpfsPlugin/Publish"
	IpfsPlugin_Delete_FullMethodName  = "/ipfs.IpfsPlugin/Delete"
	IpfsPlugin_KeyInfo_FullMethodName = "/ipfs.IpfsPlugin/KeyInfo"
)

// IpfsPluginClient is the client API for IpfsPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpfsPluginClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	KeyInfo(ctx context.Context, in *KeyInfoRequest, opts ...grpc.CallOption) (*KeyInfoResponse, error)
}

type ipfsPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewIpfsPluginClient(cc grpc.ClientConnInterface) IpfsPluginClient {
	return &ipfsPluginClient{cc}
}

func (c *ipfsPluginClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, IpfsPlugin_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsPluginClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, IpfsPlugin_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsPluginClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, IpfsPlugin_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsPluginClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, IpfsPlugin_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipfsPluginClient) KeyInfo(ctx context.Context, in *KeyInfoRequest, opts ...grpc.CallOption) (*KeyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyInfoResponse)
	err := c.cc.Invoke(ctx, IpfsPlugin_KeyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpfsPluginServer is the server API for IpfsPlugin service.
// All implementations must embed UnimplementedIpfsPluginServer
// for forward compatibility.
type IpfsPluginServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	KeyInfo(context.Context, *KeyInfoRequest) (*KeyInfoResponse, error)
	mustEmbedUnimplementedIpfsPluginServer()
}

// UnimplementedIpfsPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpfsPluginServer struct{}

func (UnimplementedIpfsPluginServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedIpfsPluginServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedIpfsPluginServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedIpfsPluginServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedIpfsPluginServer) KeyInfo(context.Context, *KeyInfoRequest) (*KeyInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyInfo not implemented")
}
func (UnimplementedIpfsPluginServer) mustEmbedUnimplementedIpfsPluginServer() {}
func (UnimplementedIpfsPluginServer) testEmbeddedByValue()                    {}

// UnsafeIpfsPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpfsPluginServer will
// result in compilation errors.
type UnsafeIpfsPluginServer interface {
	mustEmbedUnimplementedIpfsPluginServer()
}

func RegisterIpfsPluginServer(s grpc.ServiceRegistrar, srv IpfsPluginServer) {
	// If the following call panics, it indicates UnimplementedIpfsPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpfsPlugin_ServiceDesc, srv)
}

func _IpfsPlugin_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsPluginServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpfsPlugin_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsPluginServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsPlugin_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsPluginServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpfsPlugin_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsPluginServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsPlugin_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsPluginServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpfsPlugin_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsPluginServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsPlugin_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsPluginServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpfsPlugin_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsPluginServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpfsPlugin_KeyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpfsPluginServer).KeyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpfsPlugin_KeyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpfsPluginServer).KeyInfo(ctx, req.(*KeyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpfsPlugin_ServiceDesc is the grpc.ServiceDesc for IpfsPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpfsPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipfs.IpfsPlugin",
	HandlerType: (*IpfsPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _IpfsPlugin_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _IpfsPlugin_Get_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _IpfsPlugin_Publish_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IpfsPlugin_Delete_Handler,
		},
		{
			MethodName: "KeyInfo",
			Handler:    _IpfsPlugin_KeyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/ipfs.proto",
}
