// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/plugins/kms.proto

// Internal KMS plugin contract used between the gateway and the KMS gRPC plugin.
// It intentionally mirrors proto/services/kms.proto today to keep the gateway
// adapter thin, but it is allowed to diverge if internal-only fields, provider-
// specific execution details, or future threshold-crypto flows require it.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagKey        string                 `protobuf:"bytes,1,opt,name=tag_key,json=tagKey,proto3" json:"tag_key,omitempty"`
	TagValue      string                 `protobuf:"bytes,2,opt,name=tag_value,json=tagValue,proto3" json:"tag_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_plugins_kms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetTagKey() string {
	if x != nil {
		return x.TagKey
	}
	return ""
}

func (x *Tag) GetTagValue() string {
	if x != nil {
		return x.TagValue
	}
	return ""
}

type KeyMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyId          string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	KeySpec        string                 `protobuf:"bytes,3,opt,name=key_spec,json=keySpec,proto3" json:"key_spec,omitempty"`
	KeyUsage       string                 `protobuf:"bytes,4,opt,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	Enabled        bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PrimaryVersion uint32                 `protobuf:"varint,6,opt,name=primary_version,json=primaryVersion,proto3" json:"primary_version,omitempty"`
	CreationDate   string                 `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Tags           []*Tag                 `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Scheme         string                 `protobuf:"bytes,9,opt,name=scheme,proto3" json:"scheme,omitempty"`
	PublicKey      *string                `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	Address        *string                `protobuf:"bytes,11,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Alias          string                 `protobuf:"bytes,12,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyMetadata) Reset() {
	*x = KeyMetadata{}
	mi := &file_proto_plugins_kms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyMetadata) ProtoMessage() {}

func (x *KeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyMetadata.ProtoReflect.Descriptor instead.
func (*KeyMetadata) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{1}
}

func (x *KeyMetadata) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyMetadata) GetKeySpec() string {
	if x != nil {
		return x.KeySpec
	}
	return ""
}

func (x *KeyMetadata) GetKeyUsage() string {
	if x != nil {
		return x.KeyUsage
	}
	return ""
}

func (x *KeyMetadata) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *KeyMetadata) GetPrimaryVersion() uint32 {
	if x != nil {
		return x.PrimaryVersion
	}
	return 0
}

func (x *KeyMetadata) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *KeyMetadata) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KeyMetadata) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *KeyMetadata) GetPublicKey() string {
	if x != nil && x.PublicKey != nil {
		return *x.PublicKey
	}
	return ""
}

func (x *KeyMetadata) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *KeyMetadata) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type EncryptRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	KeyId               string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Plaintext           string                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	EncryptionAlgorithm *string                `protobuf:"bytes,3,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3,oneof" json:"encryption_algorithm,omitempty"`
	ClientId            string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EncryptRequest) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *EncryptRequest) GetEncryptionAlgorithm() string {
	if x != nil && x.EncryptionAlgorithm != nil {
		return *x.EncryptionAlgorithm
	}
	return ""
}

func (x *EncryptRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type EncryptResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CiphertextBlob      string                 `protobuf:"bytes,1,opt,name=ciphertext_blob,json=ciphertextBlob,proto3" json:"ciphertext_blob,omitempty"`
	KeyId               string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	EncryptionAlgorithm string                 `protobuf:"bytes,3,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptResponse) GetCiphertextBlob() string {
	if x != nil {
		return x.CiphertextBlob
	}
	return ""
}

func (x *EncryptResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EncryptResponse) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

type DecryptRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CiphertextBlob      string                 `protobuf:"bytes,1,opt,name=ciphertext_blob,json=ciphertextBlob,proto3" json:"ciphertext_blob,omitempty"`
	KeyId               *string                `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3,oneof" json:"key_id,omitempty"`
	EncryptionAlgorithm *string                `protobuf:"bytes,3,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3,oneof" json:"encryption_algorithm,omitempty"`
	ClientId            string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{4}
}

func (x *DecryptRequest) GetCiphertextBlob() string {
	if x != nil {
		return x.CiphertextBlob
	}
	return ""
}

func (x *DecryptRequest) GetKeyId() string {
	if x != nil && x.KeyId != nil {
		return *x.KeyId
	}
	return ""
}

func (x *DecryptRequest) GetEncryptionAlgorithm() string {
	if x != nil && x.EncryptionAlgorithm != nil {
		return *x.EncryptionAlgorithm
	}
	return ""
}

func (x *DecryptRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DecryptResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Plaintext           string                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	KeyId               string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	EncryptionAlgorithm string                 `protobuf:"bytes,3,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{5}
}

func (x *DecryptResponse) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *DecryptResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DecryptResponse) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

type SignRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SigningAlgorithm string                 `protobuf:"bytes,3,opt,name=signing_algorithm,json=signingAlgorithm,proto3" json:"signing_algorithm,omitempty"`
	MessageType      *string                `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3,oneof" json:"message_type,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{6}
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignRequest) GetSigningAlgorithm() string {
	if x != nil {
		return x.SigningAlgorithm
	}
	return ""
}

func (x *SignRequest) GetMessageType() string {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return ""
}

func (x *SignRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SignResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Signature        string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	SigningAlgorithm string                 `protobuf:"bytes,3,opt,name=signing_algorithm,json=signingAlgorithm,proto3" json:"signing_algorithm,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{7}
}

func (x *SignResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignResponse) GetSigningAlgorithm() string {
	if x != nil {
		return x.SigningAlgorithm
	}
	return ""
}

type CreateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	KeySpec       string                 `protobuf:"bytes,2,opt,name=key_spec,json=keySpec,proto3" json:"key_spec,omitempty"`
	KeyUsage      string                 `protobuf:"bytes,3,opt,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Scheme        *string                `protobuf:"bytes,5,opt,name=scheme,proto3,oneof" json:"scheme,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Alias         string                 `protobuf:"bytes,7,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{8}
}

func (x *CreateKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKeyRequest) GetKeySpec() string {
	if x != nil {
		return x.KeySpec
	}
	return ""
}

func (x *CreateKeyRequest) GetKeyUsage() string {
	if x != nil {
		return x.KeyUsage
	}
	return ""
}

func (x *CreateKeyRequest) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateKeyRequest) GetScheme() string {
	if x != nil && x.Scheme != nil {
		return *x.Scheme
	}
	return ""
}

func (x *CreateKeyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateKeyRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyMetadata   *KeyMetadata           `protobuf:"bytes,1,opt,name=key_metadata,json=keyMetadata,proto3" json:"key_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{9}
}

func (x *CreateKeyResponse) GetKeyMetadata() *KeyMetadata {
	if x != nil {
		return x.KeyMetadata
	}
	return nil
}

type GenerateDataKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	DataKeySpec   *string                `protobuf:"bytes,2,opt,name=data_key_spec,json=dataKeySpec,proto3,oneof" json:"data_key_spec,omitempty"`
	NumberOfBytes *uint32                `protobuf:"varint,3,opt,name=number_of_bytes,json=numberOfBytes,proto3,oneof" json:"number_of_bytes,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDataKeyRequest) Reset() {
	*x = GenerateDataKeyRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDataKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataKeyRequest) ProtoMessage() {}

func (x *GenerateDataKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateDataKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateDataKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenerateDataKeyRequest) GetDataKeySpec() string {
	if x != nil && x.DataKeySpec != nil {
		return *x.DataKeySpec
	}
	return ""
}

func (x *GenerateDataKeyRequest) GetNumberOfBytes() uint32 {
	if x != nil && x.NumberOfBytes != nil {
		return *x.NumberOfBytes
	}
	return 0
}

func (x *GenerateDataKeyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GenerateDataKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyId          string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Plaintext      string                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	CiphertextBlob string                 `protobuf:"bytes,3,opt,name=ciphertext_blob,json=ciphertextBlob,proto3" json:"ciphertext_blob,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateDataKeyResponse) Reset() {
	*x = GenerateDataKeyResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDataKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDataKeyResponse) ProtoMessage() {}

func (x *GenerateDataKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDataKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateDataKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateDataKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenerateDataKeyResponse) GetPlaintext() string {
	if x != nil {
		return x.Plaintext
	}
	return ""
}

func (x *GenerateDataKeyResponse) GetCiphertextBlob() string {
	if x != nil {
		return x.CiphertextBlob
	}
	return ""
}

type RotateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyRequest) Reset() {
	*x = RotateKeyRequest{}
	mi := &file_proto_plugins_kms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyRequest) ProtoMessage() {}

func (x *RotateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{12}
}

func (x *RotateKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RotateKeyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RotateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyMetadata   *KeyMetadata           `protobuf:"bytes,1,opt,name=key_metadata,json=keyMetadata,proto3" json:"key_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyResponse) Reset() {
	*x = RotateKeyResponse{}
	mi := &file_proto_plugins_kms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyResponse) ProtoMessage() {}

func (x *RotateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_kms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_kms_proto_rawDescGZIP(), []int{13}
}

func (x *RotateKeyResponse) GetKeyMetadata() *KeyMetadata {
	if x != nil {
		return x.KeyMetadata
	}
	return nil
}

var File_proto_plugins_kms_proto protoreflect.FileDescriptor

const file_proto_plugins_kms_proto_rawDesc = "" +
	"\n" +
	"\x17proto/plugins/kms.proto\x12\x06kmsapi\";\n" +
	"\x03Tag\x12\x17\n" +
	"\atag_key\x18\x01 \x01(\tR\x06tagKey\x12\x1b\n" +
	"\ttag_value\x18\x02 \x01(\tR\btagValue\"\x93\x03\n" +
	"\vKeyMetadata\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bkey_spec\x18\x03 \x01(\tR\akeySpec\x12\x1b\n" +
	"\tkey_usage\x18\x04 \x01(\tR\bkeyUsage\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12'\n" +
	"\x0fprimary_version\x18\x06 \x01(\rR\x0eprimaryVersion\x12#\n" +
	"\rcreation_date\x18\a \x01(\tR\fcreationDate\x12\x1f\n" +
	"\x04tags\x18\b \x03(\v2\v.kmsapi.TagR\x04tags\x12\x16\n" +
	"\x06scheme\x18\t \x01(\tR\x06scheme\x12\"\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\tH\x00R\tpublicKey\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\v \x01(\tH\x01R\aaddress\x88\x01\x01\x12\x14\n" +
	"\x05alias\x18\f \x01(\tR\x05aliasB\r\n" +
	"\v_public_keyB\n" +
	"\n" +
	"\b_address\"\xb3\x01\n" +
	"\x0eEncryptRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\tR\tplaintext\x126\n" +
	"\x14encryption_algorithm\x18\x03 \x01(\tH\x00R\x13encryptionAlgorithm\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientIdB\x17\n" +
	"\x15_encryption_algorithm\"\x84\x01\n" +
	"\x0fEncryptResponse\x12'\n" +
	"\x0fciphertext_blob\x18\x01 \x01(\tR\x0eciphertextBlob\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x121\n" +
	"\x14encryption_algorithm\x18\x03 \x01(\tR\x13encryptionAlgorithm\"\xce\x01\n" +
	"\x0eDecryptRequest\x12'\n" +
	"\x0fciphertext_blob\x18\x01 \x01(\tR\x0eciphertextBlob\x12\x1a\n" +
	"\x06key_id\x18\x02 \x01(\tH\x00R\x05keyId\x88\x01\x01\x126\n" +
	"\x14encryption_algorithm\x18\x03 \x01(\tH\x01R\x13encryptionAlgorithm\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientIdB\t\n" +
	"\a_key_idB\x17\n" +
	"\x15_encryption_algorithm\"y\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\tR\tplaintext\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x121\n" +
	"\x14encryption_algorithm\x18\x03 \x01(\tR\x13encryptionAlgorithm\"\xc1\x01\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11signing_algorithm\x18\x03 \x01(\tR\x10signingAlgorithm\x12&\n" +
	"\fmessage_type\x18\x04 \x01(\tH\x00R\vmessageType\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientIdB\x0f\n" +
	"\r_message_type\"p\n" +
	"\fSignResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12+\n" +
	"\x11signing_algorithm\x18\x03 \x01(\tR\x10signingAlgorithm\"\xe8\x01\n" +
	"\x10CreateKeyRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x19\n" +
	"\bkey_spec\x18\x02 \x01(\tR\akeySpec\x12\x1b\n" +
	"\tkey_usage\x18\x03 \x01(\tR\bkeyUsage\x12\x1f\n" +
	"\x04tags\x18\x04 \x03(\v2\v.kmsapi.TagR\x04tags\x12\x1b\n" +
	"\x06scheme\x18\x05 \x01(\tH\x00R\x06scheme\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x14\n" +
	"\x05alias\x18\a \x01(\tR\x05aliasB\t\n" +
	"\a_scheme\"K\n" +
	"\x11CreateKeyResponse\x126\n" +
	"\fkey_metadata\x18\x01 \x01(\v2\x13.kmsapi.KeyMetadataR\vkeyMetadata\"\xc8\x01\n" +
	"\x16GenerateDataKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12'\n" +
	"\rdata_key_spec\x18\x02 \x01(\tH\x00R\vdataKeySpec\x88\x01\x01\x12+\n" +
	"\x0fnumber_of_bytes\x18\x03 \x01(\rH\x01R\rnumberOfBytes\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientIdB\x10\n" +
	"\x0e_data_key_specB\x12\n" +
	"\x10_number_of_bytes\"w\n" +
	"\x17GenerateDataKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\tR\tplaintext\x12'\n" +
	"\x0fciphertext_blob\x18\x03 \x01(\tR\x0eciphertextBlob\"F\n" +
	"\x10RotateKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"K\n" +
	"\x11RotateKeyResponse\x126\n" +
	"\fkey_metadata\x18\x01 \x01(\v2\x13.kmsapi.KeyMetadataR\vkeyMetadata2\x8e\x03\n" +
	"\tKmsPlugin\x12:\n" +
	"\aEncrypt\x12\x16.kmsapi.EncryptRequest\x1a\x17.kmsapi.EncryptResponse\x12:\n" +
	"\aDecrypt\x12\x16.kmsapi.DecryptRequest\x1a\x17.kmsapi.DecryptResponse\x121\n" +
	"\x04Sign\x12\x13.kmsapi.SignRequest\x1a\x14.kmsapi.SignResponse\x12@\n" +
	"\tCreateKey\x12\x18.kmsapi.CreateKeyRequest\x1a\x19.kmsapi.CreateKeyResponse\x12R\n" +
	"\x0fGenerateDataKey\x12\x1e.kmsapi.GenerateDataKeyRequest\x1a\x1f.kmsapi.GenerateDataKeyResponse\x12@\n" +
	"\tRotateKey\x12\x18.kmsapi.RotateKeyRequest\x1a\x19.kmsapi.RotateKeyResponseB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_plugins_kms_proto_rawDescOnce sync.Once
	file_proto_plugins_kms_proto_rawDescData []byte
)

func file_proto_plugins_kms_proto_rawDescGZIP() []byte {
	file_proto_plugins_kms_proto_rawDescOnce.Do(func() {
		file_proto_plugins_kms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugins_kms_proto_rawDesc), len(file_proto_plugins_kms_proto_rawDesc)))
	})
	return file_proto_plugins_kms_proto_rawDescData
}

var file_proto_plugins_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_plugins_kms_proto_goTypes = []any{
	(*Tag)(nil),                     // 0: kmsapi.Tag
	(*KeyMetadata)(nil),             // 1: kmsapi.KeyMetadata
	(*EncryptRequest)(nil),          // 2: kmsapi.EncryptRequest
	(*EncryptResponse)(nil),         // 3: kmsapi.EncryptResponse
	(*DecryptRequest)(nil),          // 4: kmsapi.DecryptRequest
	(*DecryptResponse)(nil),         // 5: kmsapi.DecryptResponse
	(*SignRequest)(nil),             // 6: kmsapi.SignRequest
	(*SignResponse)(nil),            // 7: kmsapi.SignResponse
	(*CreateKeyRequest)(nil),        // 8: kmsapi.CreateKeyRequest
	(*CreateKeyResponse)(nil),       // 9: kmsapi.CreateKeyResponse
	(*GenerateDataKeyRequest)(nil),  // 10: kmsapi.GenerateDataKeyRequest
	(*GenerateDataKeyResponse)(nil), // 11: kmsapi.GenerateDataKeyResponse
	(*RotateKeyRequest)(nil),        // 12: kmsapi.RotateKeyRequest
	(*RotateKeyResponse)(nil),       // 13: kmsapi.RotateKeyResponse
}
var file_proto_plugins_kms_proto_depIdxs = []int32{
	0,  // 0: kmsapi.KeyMetadata.tags:type_name -> kmsapi.Tag
	0,  // 1: kmsapi.CreateKeyRequest.tags:type_name -> kmsapi.Tag
	1,  // 2: kmsapi.CreateKeyResponse.key_metadata:type_name -> kmsapi.KeyMetadata
	1,  // 3: kmsapi.RotateKeyResponse.key_metadata:type_name -> kmsapi.KeyMetadata
	2,  // 4: kmsapi.KmsPlugin.Encrypt:input_type -> kmsapi.EncryptRequest
	4,  // 5: kmsapi.KmsPlugin.Decrypt:input_type -> kmsapi.DecryptRequest
	6,  // 6: kmsapi.KmsPlugin.Sign:input_type -> kmsapi.SignRequest
	8,  // 7: kmsapi.KmsPlugin.CreateKey:input_type -> kmsapi.CreateKeyRequest
	10, // 8: kmsapi.KmsPlugin.GenerateDataKey:input_type -> kmsapi.GenerateDataKeyRequest
	12, // 9: kmsapi.KmsPlugin.RotateKey:input_type -> kmsapi.RotateKeyRequest
	3,  // 10: kmsapi.KmsPlugin.Encrypt:output_type -> kmsapi.EncryptResponse
	5,  // 11: kmsapi.KmsPlugin.Decrypt:output_type -> kmsapi.DecryptResponse
	7,  // 12: kmsapi.KmsPlugin.Sign:output_type -> kmsapi.SignResponse
	9,  // 13: kmsapi.KmsPlugin.CreateKey:output_type -> kmsapi.CreateKeyResponse
	11, // 14: kmsapi.KmsPlugin.GenerateDataKey:output_type -> kmsapi.GenerateDataKeyResponse
	13, // 15: kmsapi.KmsPlugin.RotateKey:output_type -> kmsapi.RotateKeyResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_plugins_kms_proto_init() }
func file_proto_plugins_kms_proto_init() {
	if File_proto_plugins_kms_proto != nil {
		return
	}
	file_proto_plugins_kms_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_plugins_kms_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_plugins_kms_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_plugins_kms_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_plugins_kms_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_plugins_kms_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugins_kms_proto_rawDesc), len(file_proto_plugins_kms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugins_kms_proto_goTypes,
		DependencyIndexes: file_proto_plugins_kms_proto_depIdxs,
		MessageInfos:      file_proto_plugins_kms_proto_msgTypes,
	}.Build()
	File_proto_plugins_kms_proto = out.File
	file_proto_plugins_kms_proto_goTypes = nil
	file_proto_plugins_kms_proto_depIdxs = nil
}
