// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/plugins/kms.proto

// Internal KMS plugin contract used between the gateway and the KMS gRPC plugin.
// It intentionally mirrors proto/services/kms.proto today to keep the gateway
// adapter thin, but it is allowed to diverge if internal-only fields, provider-
// specific execution details, or future threshold-crypto flows require it.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KmsPlugin_Encrypt_FullMethodName         = "/kmsapi.KmsPlugin/Encrypt"
	KmsPlugin_Decrypt_FullMethodName         = "/kmsapi.KmsPlugin/Decrypt"
	KmsPlugin_Sign_FullMethodName            = "/kmsapi.KmsPlugin/Sign"
	KmsPlugin_Encapsulate_FullMethodName     = "/kmsapi.KmsPlugin/Encapsulate"
	KmsPlugin_Decapsulate_FullMethodName     = "/kmsapi.KmsPlugin/Decapsulate"
	KmsPlugin_CreateKey_FullMethodName       = "/kmsapi.KmsPlugin/CreateKey"
	KmsPlugin_GenerateDataKey_FullMethodName = "/kmsapi.KmsPlugin/GenerateDataKey"
	KmsPlugin_RotateKey_FullMethodName       = "/kmsapi.KmsPlugin/RotateKey"
	KmsPlugin_Put_FullMethodName             = "/kmsapi.KmsPlugin/Put"
	KmsPlugin_Export_FullMethodName          = "/kmsapi.KmsPlugin/Export"
	KmsPlugin_Unwrap_FullMethodName          = "/kmsapi.KmsPlugin/Unwrap"
	KmsPlugin_List_FullMethodName            = "/kmsapi.KmsPlugin/List"
	KmsPlugin_Delete_FullMethodName          = "/kmsapi.KmsPlugin/Delete"
)

// KmsPluginClient is the client API for KmsPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KmsPluginClient interface {
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Encapsulate(ctx context.Context, in *EncapsulateRequest, opts ...grpc.CallOption) (*EncapsulateResponse, error)
	Decapsulate(ctx context.Context, in *DecapsulateRequest, opts ...grpc.CallOption) (*DecapsulateResponse, error)
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	GenerateDataKey(ctx context.Context, in *GenerateDataKeyRequest, opts ...grpc.CallOption) (*GenerateDataKeyResponse, error)
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
	Put(ctx context.Context, in *KeyStorePutRequest, opts ...grpc.CallOption) (*KeyStorePutResponse, error)
	Export(ctx context.Context, in *KeyStoreExportRequest, opts ...grpc.CallOption) (*KeyStoreExportResponse, error)
	Unwrap(ctx context.Context, in *KeyStoreUnwrapRequest, opts ...grpc.CallOption) (*KeyStoreUnwrapResponse, error)
	List(ctx context.Context, in *KeyStoreListRequest, opts ...grpc.CallOption) (*KeyStoreListResponse, error)
	Delete(ctx context.Context, in *KeyStoreDeleteRequest, opts ...grpc.CallOption) (*KeyStoreDeleteResponse, error)
}

type kmsPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewKmsPluginClient(cc grpc.ClientConnInterface) KmsPluginClient {
	return &kmsPluginClient{cc}
}

func (c *kmsPluginClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Encapsulate(ctx context.Context, in *EncapsulateRequest, opts ...grpc.CallOption) (*EncapsulateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncapsulateResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Encapsulate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Decapsulate(ctx context.Context, in *DecapsulateRequest, opts ...grpc.CallOption) (*DecapsulateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecapsulateResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Decapsulate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_CreateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) GenerateDataKey(ctx context.Context, in *GenerateDataKeyRequest, opts ...grpc.CallOption) (*GenerateDataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDataKeyResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_GenerateDataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Put(ctx context.Context, in *KeyStorePutRequest, opts ...grpc.CallOption) (*KeyStorePutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStorePutResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Export(ctx context.Context, in *KeyStoreExportRequest, opts ...grpc.CallOption) (*KeyStoreExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStoreExportResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Unwrap(ctx context.Context, in *KeyStoreUnwrapRequest, opts ...grpc.CallOption) (*KeyStoreUnwrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStoreUnwrapResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Unwrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) List(ctx context.Context, in *KeyStoreListRequest, opts ...grpc.CallOption) (*KeyStoreListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStoreListResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsPluginClient) Delete(ctx context.Context, in *KeyStoreDeleteRequest, opts ...grpc.CallOption) (*KeyStoreDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStoreDeleteResponse)
	err := c.cc.Invoke(ctx, KmsPlugin_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KmsPluginServer is the server API for KmsPlugin service.
// All implementations must embed UnimplementedKmsPluginServer
// for forward compatibility.
type KmsPluginServer interface {
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Encapsulate(context.Context, *EncapsulateRequest) (*EncapsulateResponse, error)
	Decapsulate(context.Context, *DecapsulateRequest) (*DecapsulateResponse, error)
	CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	GenerateDataKey(context.Context, *GenerateDataKeyRequest) (*GenerateDataKeyResponse, error)
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
	Put(context.Context, *KeyStorePutRequest) (*KeyStorePutResponse, error)
	Export(context.Context, *KeyStoreExportRequest) (*KeyStoreExportResponse, error)
	Unwrap(context.Context, *KeyStoreUnwrapRequest) (*KeyStoreUnwrapResponse, error)
	List(context.Context, *KeyStoreListRequest) (*KeyStoreListResponse, error)
	Delete(context.Context, *KeyStoreDeleteRequest) (*KeyStoreDeleteResponse, error)
	mustEmbedUnimplementedKmsPluginServer()
}

// UnimplementedKmsPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKmsPluginServer struct{}

func (UnimplementedKmsPluginServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedKmsPluginServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedKmsPluginServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedKmsPluginServer) Encapsulate(context.Context, *EncapsulateRequest) (*EncapsulateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encapsulate not implemented")
}
func (UnimplementedKmsPluginServer) Decapsulate(context.Context, *DecapsulateRequest) (*DecapsulateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decapsulate not implemented")
}
func (UnimplementedKmsPluginServer) CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedKmsPluginServer) GenerateDataKey(context.Context, *GenerateDataKeyRequest) (*GenerateDataKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDataKey not implemented")
}
func (UnimplementedKmsPluginServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedKmsPluginServer) Put(context.Context, *KeyStorePutRequest) (*KeyStorePutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKmsPluginServer) Export(context.Context, *KeyStoreExportRequest) (*KeyStoreExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedKmsPluginServer) Unwrap(context.Context, *KeyStoreUnwrapRequest) (*KeyStoreUnwrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unwrap not implemented")
}
func (UnimplementedKmsPluginServer) List(context.Context, *KeyStoreListRequest) (*KeyStoreListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKmsPluginServer) Delete(context.Context, *KeyStoreDeleteRequest) (*KeyStoreDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKmsPluginServer) mustEmbedUnimplementedKmsPluginServer() {}
func (UnimplementedKmsPluginServer) testEmbeddedByValue()                   {}

// UnsafeKmsPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KmsPluginServer will
// result in compilation errors.
type UnsafeKmsPluginServer interface {
	mustEmbedUnimplementedKmsPluginServer()
}

func RegisterKmsPluginServer(s grpc.ServiceRegistrar, srv KmsPluginServer) {
	// If the following call panics, it indicates UnimplementedKmsPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KmsPlugin_ServiceDesc, srv)
}

func _KmsPlugin_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Encapsulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncapsulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Encapsulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Encapsulate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Encapsulate(ctx, req.(*EncapsulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Decapsulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecapsulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Decapsulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Decapsulate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Decapsulate(ctx, req.(*DecapsulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_GenerateDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).GenerateDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_GenerateDataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).GenerateDataKey(ctx, req.(*GenerateDataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStorePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Put(ctx, req.(*KeyStorePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStoreExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Export(ctx, req.(*KeyStoreExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Unwrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStoreUnwrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Unwrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Unwrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Unwrap(ctx, req.(*KeyStoreUnwrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStoreListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).List(ctx, req.(*KeyStoreListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsPlugin_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStoreDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsPluginServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KmsPlugin_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsPluginServer).Delete(ctx, req.(*KeyStoreDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KmsPlugin_ServiceDesc is the grpc.ServiceDesc for KmsPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KmsPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kmsapi.KmsPlugin",
	HandlerType: (*KmsPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _KmsPlugin_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _KmsPlugin_Decrypt_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _KmsPlugin_Sign_Handler,
		},
		{
			MethodName: "Encapsulate",
			Handler:    _KmsPlugin_Encapsulate_Handler,
		},
		{
			MethodName: "Decapsulate",
			Handler:    _KmsPlugin_Decapsulate_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _KmsPlugin_CreateKey_Handler,
		},
		{
			MethodName: "GenerateDataKey",
			Handler:    _KmsPlugin_GenerateDataKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _KmsPlugin_RotateKey_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KmsPlugin_Put_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _KmsPlugin_Export_Handler,
		},
		{
			MethodName: "Unwrap",
			Handler:    _KmsPlugin_Unwrap_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KmsPlugin_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KmsPlugin_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/kms.proto",
}
