// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/plugins/patissuer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatIssuerPlugin_IssueToken_FullMethodName = "/patissuer.PatIssuerPlugin/IssueToken"
	PatIssuerPlugin_GetJwks_FullMethodName    = "/patissuer.PatIssuerPlugin/GetJwks"
)

// PatIssuerPluginClient is the client API for PatIssuerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PatIssuerPlugin mints Personal Access Tokens (Model B): compact JWS signed
// with the platform signing key. The dashboard owns the PAT metadata row
// (jti) and the charge flow; this plugin owns claims assembly and signing.
// Verifiers fetch the public keys via GetJwks.
type PatIssuerPluginClient interface {
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	GetJwks(ctx context.Context, in *GetJwksRequest, opts ...grpc.CallOption) (*GetJwksResponse, error)
}

type patIssuerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPatIssuerPluginClient(cc grpc.ClientConnInterface) PatIssuerPluginClient {
	return &patIssuerPluginClient{cc}
}

func (c *patIssuerPluginClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, PatIssuerPlugin_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patIssuerPluginClient) GetJwks(ctx context.Context, in *GetJwksRequest, opts ...grpc.CallOption) (*GetJwksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJwksResponse)
	err := c.cc.Invoke(ctx, PatIssuerPlugin_GetJwks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatIssuerPluginServer is the server API for PatIssuerPlugin service.
// All implementations must embed UnimplementedPatIssuerPluginServer
// for forward compatibility.
//
// PatIssuerPlugin mints Personal Access Tokens (Model B): compact JWS signed
// with the platform signing key. The dashboard owns the PAT metadata row
// (jti) and the charge flow; this plugin owns claims assembly and signing.
// Verifiers fetch the public keys via GetJwks.
type PatIssuerPluginServer interface {
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	GetJwks(context.Context, *GetJwksRequest) (*GetJwksResponse, error)
	mustEmbedUnimplementedPatIssuerPluginServer()
}

// UnimplementedPatIssuerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatIssuerPluginServer struct{}

func (UnimplementedPatIssuerPluginServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedPatIssuerPluginServer) GetJwks(context.Context, *GetJwksRequest) (*GetJwksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJwks not implemented")
}
func (UnimplementedPatIssuerPluginServer) mustEmbedUnimplementedPatIssuerPluginServer() {}
func (UnimplementedPatIssuerPluginServer) testEmbeddedByValue()                         {}

// UnsafePatIssuerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatIssuerPluginServer will
// result in compilation errors.
type UnsafePatIssuerPluginServer interface {
	mustEmbedUnimplementedPatIssuerPluginServer()
}

func RegisterPatIssuerPluginServer(s grpc.ServiceRegistrar, srv PatIssuerPluginServer) {
	// If the following call panics, it indicates UnimplementedPatIssuerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatIssuerPlugin_ServiceDesc, srv)
}

func _PatIssuerPlugin_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatIssuerPluginServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatIssuerPlugin_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatIssuerPluginServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatIssuerPlugin_GetJwks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatIssuerPluginServer).GetJwks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatIssuerPlugin_GetJwks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatIssuerPluginServer).GetJwks(ctx, req.(*GetJwksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatIssuerPlugin_ServiceDesc is the grpc.ServiceDesc for PatIssuerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatIssuerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patissuer.PatIssuerPlugin",
	HandlerType: (*PatIssuerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _PatIssuerPlugin_IssueToken_Handler,
		},
		{
			MethodName: "GetJwks",
			Handler:    _PatIssuerPlugin_GetJwks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/patissuer.proto",
}
