// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/plugins/patissuer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PersonalAccessToken.id from the dashboard — becomes the jti claim,
	// the revocation key on the Hold path.
	Jti string `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	// Account.id — becomes the sub claim.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Frozen per-account KMS namespace input (D9) — carried as the
	// kms_tenant claim. May be empty until the D9 backfill lands.
	KmsTenant string `protobuf:"bytes,3,opt,name=kms_tenant,json=kmsTenant,proto3" json:"kms_tenant,omitempty"`
	// Expiry as unix seconds. iat/exp are the issuer's responsibility to
	// stamp; the request only bounds the lifetime.
	ExpiresAt     int64 `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_proto_plugins_patissuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_patissuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_patissuer_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *IssueTokenRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssueTokenRequest) GetKmsTenant() string {
	if x != nil {
		return x.KmsTenant
	}
	return ""
}

func (x *IssueTokenRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type IssueTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Compact JWS (header.payload.signature).
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_proto_plugins_patissuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_patissuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_patissuer_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetJwksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksRequest) Reset() {
	*x = GetJwksRequest{}
	mi := &file_proto_plugins_patissuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksRequest) ProtoMessage() {}

func (x *GetJwksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_patissuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksRequest.ProtoReflect.Descriptor instead.
func (*GetJwksRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_patissuer_proto_rawDescGZIP(), []int{2}
}

type GetJwksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC 7517 JWK Set JSON — public keys only, kid-selected by verifiers.
	JwksJson      string `protobuf:"bytes,1,opt,name=jwks_json,json=jwksJson,proto3" json:"jwks_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksResponse) Reset() {
	*x = GetJwksResponse{}
	mi := &file_proto_plugins_patissuer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksResponse) ProtoMessage() {}

func (x *GetJwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_patissuer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksResponse.ProtoReflect.Descriptor instead.
func (*GetJwksResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_patissuer_proto_rawDescGZIP(), []int{3}
}

func (x *GetJwksResponse) GetJwksJson() string {
	if x != nil {
		return x.JwksJson
	}
	return ""
}

var File_proto_plugins_patissuer_proto protoreflect.FileDescriptor

const file_proto_plugins_patissuer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/plugins/patissuer.proto\x12\tpatissuer\"}\n" +
	"\x11IssueTokenRequest\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"kms_tenant\x18\x03 \x01(\tR\tkmsTenant\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"P\n" +
	"\x12IssueTokenResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x10\n" +
	"\x0eGetJwksRequest\".\n" +
	"\x0fGetJwksResponse\x12\x1b\n" +
	"\tjwks_json\x18\x01 \x01(\tR\bjwksJson2\x9e\x01\n" +
	"\x0fPatIssuerPlugin\x12I\n" +
	"\n" +
	"IssueToken\x12\x1c.patissuer.IssueTokenRequest\x1a\x1d.patissuer.IssueTokenResponse\x12@\n" +
	"\aGetJwks\x12\x19.patissuer.GetJwksRequest\x1a\x1a.patissuer.GetJwksResponseB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_plugins_patissuer_proto_rawDescOnce sync.Once
	file_proto_plugins_patissuer_proto_rawDescData []byte
)

func file_proto_plugins_patissuer_proto_rawDescGZIP() []byte {
	file_proto_plugins_patissuer_proto_rawDescOnce.Do(func() {
		file_proto_plugins_patissuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugins_patissuer_proto_rawDesc), len(file_proto_plugins_patissuer_proto_rawDesc)))
	})
	return file_proto_plugins_patissuer_proto_rawDescData
}

var file_proto_plugins_patissuer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_plugins_patissuer_proto_goTypes = []any{
	(*IssueTokenRequest)(nil),  // 0: patissuer.IssueTokenRequest
	(*IssueTokenResponse)(nil), // 1: patissuer.IssueTokenResponse
	(*GetJwksRequest)(nil),     // 2: patissuer.GetJwksRequest
	(*GetJwksResponse)(nil),    // 3: patissuer.GetJwksResponse
}
var file_proto_plugins_patissuer_proto_depIdxs = []int32{
	0, // 0: patissuer.PatIssuerPlugin.IssueToken:input_type -> patissuer.IssueTokenRequest
	2, // 1: patissuer.PatIssuerPlugin.GetJwks:input_type -> patissuer.GetJwksRequest
	1, // 2: patissuer.PatIssuerPlugin.IssueToken:output_type -> patissuer.IssueTokenResponse
	3, // 3: patissuer.PatIssuerPlugin.GetJwks:output_type -> patissuer.GetJwksResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_plugins_patissuer_proto_init() }
func file_proto_plugins_patissuer_proto_init() {
	if File_proto_plugins_patissuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugins_patissuer_proto_rawDesc), len(file_proto_plugins_patissuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugins_patissuer_proto_goTypes,
		DependencyIndexes: file_proto_plugins_patissuer_proto_depIdxs,
		MessageInfos:      file_proto_plugins_patissuer_proto_msgTypes,
	}.Build()
	File_proto_plugins_patissuer_proto = out.File
	file_proto_plugins_patissuer_proto_goTypes = nil
	file_proto_plugins_patissuer_proto_depIdxs = nil
}
