// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/plugins/threshold.proto

// Internal Threshold plugin contract used between the gateway and the
// Orbitport threshold gRPC plugin.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PartyIndex    int32                  `protobuf:"varint,2,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	OpenbaoUrl    string                 `protobuf:"bytes,3,opt,name=openbao_url,json=openbaoUrl,proto3" json:"openbao_url,omitempty"`
	Mount         string                 `protobuf:"bytes,4,opt,name=mount,proto3" json:"mount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMember) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GroupMember) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *GroupMember) GetOpenbaoUrl() string {
	if x != nil {
		return x.OpenbaoUrl
	}
	return ""
}

func (x *GroupMember) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

type DkgNodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	PendingFrom   []string               `protobuf:"bytes,5,rep,name=pending_from,json=pendingFrom,proto3" json:"pending_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkgNodeStatus) Reset() {
	*x = DkgNodeStatus{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkgNodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgNodeStatus) ProtoMessage() {}

func (x *DkgNodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgNodeStatus.ProtoReflect.Descriptor instead.
func (*DkgNodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{1}
}

func (x *DkgNodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DkgNodeStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DkgNodeStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DkgNodeStatus) GetPendingFrom() []string {
	if x != nil {
		return x.PendingFrom
	}
	return nil
}

type DkgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Threshold     int32                  `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Participants  []*GroupMember         `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkgRequest) Reset() {
	*x = DkgRequest{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgRequest) ProtoMessage() {}

func (x *DkgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgRequest.ProtoReflect.Descriptor instead.
func (*DkgRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{2}
}

func (x *DkgRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *DkgRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DkgRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DkgRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *DkgRequest) GetParticipants() []*GroupMember {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *DkgRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DkgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Nodes         []*DkgNodeStatus       `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	PublicKey     string                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DkgResponse) Reset() {
	*x = DkgResponse{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DkgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DkgResponse) ProtoMessage() {}

func (x *DkgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DkgResponse.ProtoReflect.Descriptor instead.
func (*DkgResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{3}
}

func (x *DkgResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *DkgResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *DkgResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DkgResponse) GetNodes() []*DkgNodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DkgResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SignNodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	PendingFrom   []string               `protobuf:"bytes,4,rep,name=pending_from,json=pendingFrom,proto3" json:"pending_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignNodeStatus) Reset() {
	*x = SignNodeStatus{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignNodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignNodeStatus) ProtoMessage() {}

func (x *SignNodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignNodeStatus.ProtoReflect.Descriptor instead.
func (*SignNodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{4}
}

func (x *SignNodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SignNodeStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SignNodeStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SignNodeStatus) GetPendingFrom() []string {
	if x != nil {
		return x.PendingFrom
	}
	return nil
}

type ThresholdSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Participants  []*GroupMember         `protobuf:"bytes,6,rep,name=participants,proto3" json:"participants,omitempty"`
	ClientId      string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdSignRequest) Reset() {
	*x = ThresholdSignRequest{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdSignRequest) ProtoMessage() {}

func (x *ThresholdSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdSignRequest.ProtoReflect.Descriptor instead.
func (*ThresholdSignRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{5}
}

func (x *ThresholdSignRequest) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *ThresholdSignRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ThresholdSignRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThresholdSignRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ThresholdSignRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *ThresholdSignRequest) GetParticipants() []*GroupMember {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ThresholdSignRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ThresholdSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Nodes         []*SignNodeStatus      `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThresholdSignResponse) Reset() {
	*x = ThresholdSignResponse{}
	mi := &file_proto_plugins_threshold_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThresholdSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdSignResponse) ProtoMessage() {}

func (x *ThresholdSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugins_threshold_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdSignResponse.ProtoReflect.Descriptor instead.
func (*ThresholdSignResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugins_threshold_proto_rawDescGZIP(), []int{6}
}

func (x *ThresholdSignResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *ThresholdSignResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ThresholdSignResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThresholdSignResponse) GetNodes() []*SignNodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ThresholdSignResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_proto_plugins_threshold_proto protoreflect.FileDescriptor

const file_proto_plugins_threshold_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/plugins/threshold.proto\x12\fthresholdapi\"~\n" +
	"\vGroupMember\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vparty_index\x18\x02 \x01(\x05R\n" +
	"partyIndex\x12\x1f\n" +
	"\vopenbao_url\x18\x03 \x01(\tR\n" +
	"openbaoUrl\x12\x14\n" +
	"\x05mount\x18\x04 \x01(\tR\x05mount\"y\n" +
	"\rDkgNodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12!\n" +
	"\fpending_from\x18\x05 \x03(\tR\vpendingFrom\"\xdf\x01\n" +
	"\n" +
	"DkgRequest\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x05R\tthreshold\x12=\n" +
	"\fparticipants\x18\x05 \x03(\v2\x19.thresholdapi.GroupMemberR\fparticipants\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\"\xb8\x01\n" +
	"\vDkgResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x121\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1b.thresholdapi.DkgNodeStatusR\x05nodes\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\tR\tpublicKey\"z\n" +
	"\x0eSignNodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12!\n" +
	"\fpending_from\x18\x04 \x03(\tR\vpendingFrom\"\x83\x02\n" +
	"\x14ThresholdSignRequest\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12=\n" +
	"\fparticipants\x18\x06 \x03(\v2\x19.thresholdapi.GroupMemberR\fparticipants\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\"\xc2\x01\n" +
	"\x15ThresholdSignResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x122\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1c.thresholdapi.SignNodeStatusR\x05nodes\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature2\xb2\x01\n" +
	"\x0fThresholdPlugin\x12D\n" +
	"\rCoordinateDkg\x12\x18.thresholdapi.DkgRequest\x1a\x19.thresholdapi.DkgResponse\x12Y\n" +
	"\x0eCoordinateSign\x12\".thresholdapi.ThresholdSignRequest\x1a#.thresholdapi.ThresholdSignResponseB5Z3github.com/spacecomputer-io/orbitport/plugins/protob\x06proto3"

var (
	file_proto_plugins_threshold_proto_rawDescOnce sync.Once
	file_proto_plugins_threshold_proto_rawDescData []byte
)

func file_proto_plugins_threshold_proto_rawDescGZIP() []byte {
	file_proto_plugins_threshold_proto_rawDescOnce.Do(func() {
		file_proto_plugins_threshold_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugins_threshold_proto_rawDesc), len(file_proto_plugins_threshold_proto_rawDesc)))
	})
	return file_proto_plugins_threshold_proto_rawDescData
}

var file_proto_plugins_threshold_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_plugins_threshold_proto_goTypes = []any{
	(*GroupMember)(nil),           // 0: thresholdapi.GroupMember
	(*DkgNodeStatus)(nil),         // 1: thresholdapi.DkgNodeStatus
	(*DkgRequest)(nil),            // 2: thresholdapi.DkgRequest
	(*DkgResponse)(nil),           // 3: thresholdapi.DkgResponse
	(*SignNodeStatus)(nil),        // 4: thresholdapi.SignNodeStatus
	(*ThresholdSignRequest)(nil),  // 5: thresholdapi.ThresholdSignRequest
	(*ThresholdSignResponse)(nil), // 6: thresholdapi.ThresholdSignResponse
}
var file_proto_plugins_threshold_proto_depIdxs = []int32{
	0, // 0: thresholdapi.DkgRequest.participants:type_name -> thresholdapi.GroupMember
	1, // 1: thresholdapi.DkgResponse.nodes:type_name -> thresholdapi.DkgNodeStatus
	0, // 2: thresholdapi.ThresholdSignRequest.participants:type_name -> thresholdapi.GroupMember
	4, // 3: thresholdapi.ThresholdSignResponse.nodes:type_name -> thresholdapi.SignNodeStatus
	2, // 4: thresholdapi.ThresholdPlugin.CoordinateDkg:input_type -> thresholdapi.DkgRequest
	5, // 5: thresholdapi.ThresholdPlugin.CoordinateSign:input_type -> thresholdapi.ThresholdSignRequest
	3, // 6: thresholdapi.ThresholdPlugin.CoordinateDkg:output_type -> thresholdapi.DkgResponse
	6, // 7: thresholdapi.ThresholdPlugin.CoordinateSign:output_type -> thresholdapi.ThresholdSignResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_plugins_threshold_proto_init() }
func file_proto_plugins_threshold_proto_init() {
	if File_proto_plugins_threshold_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugins_threshold_proto_rawDesc), len(file_proto_plugins_threshold_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugins_threshold_proto_goTypes,
		DependencyIndexes: file_proto_plugins_threshold_proto_depIdxs,
		MessageInfos:      file_proto_plugins_threshold_proto_msgTypes,
	}.Build()
	File_proto_plugins_threshold_proto = out.File
	file_proto_plugins_threshold_proto_goTypes = nil
	file_proto_plugins_threshold_proto_depIdxs = nil
}
