// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/plugins/threshold.proto

// Internal Threshold plugin contract used between the gateway and the
// Orbitport threshold gRPC plugin.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThresholdPlugin_CoordinateDkg_FullMethodName = "/thresholdapi.ThresholdPlugin/CoordinateDkg"
)

// ThresholdPluginClient is the client API for ThresholdPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThresholdPluginClient interface {
	CoordinateDkg(ctx context.Context, in *DkgRequest, opts ...grpc.CallOption) (*DkgResponse, error)
}

type thresholdPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewThresholdPluginClient(cc grpc.ClientConnInterface) ThresholdPluginClient {
	return &thresholdPluginClient{cc}
}

func (c *thresholdPluginClient) CoordinateDkg(ctx context.Context, in *DkgRequest, opts ...grpc.CallOption) (*DkgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DkgResponse)
	err := c.cc.Invoke(ctx, ThresholdPlugin_CoordinateDkg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThresholdPluginServer is the server API for ThresholdPlugin service.
// All implementations must embed UnimplementedThresholdPluginServer
// for forward compatibility.
type ThresholdPluginServer interface {
	CoordinateDkg(context.Context, *DkgRequest) (*DkgResponse, error)
	mustEmbedUnimplementedThresholdPluginServer()
}

// UnimplementedThresholdPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThresholdPluginServer struct{}

func (UnimplementedThresholdPluginServer) CoordinateDkg(context.Context, *DkgRequest) (*DkgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CoordinateDkg not implemented")
}
func (UnimplementedThresholdPluginServer) mustEmbedUnimplementedThresholdPluginServer() {}
func (UnimplementedThresholdPluginServer) testEmbeddedByValue()                         {}

// UnsafeThresholdPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThresholdPluginServer will
// result in compilation errors.
type UnsafeThresholdPluginServer interface {
	mustEmbedUnimplementedThresholdPluginServer()
}

func RegisterThresholdPluginServer(s grpc.ServiceRegistrar, srv ThresholdPluginServer) {
	// If the following call panics, it indicates UnimplementedThresholdPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThresholdPlugin_ServiceDesc, srv)
}

func _ThresholdPlugin_CoordinateDkg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DkgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThresholdPluginServer).CoordinateDkg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThresholdPlugin_CoordinateDkg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThresholdPluginServer).CoordinateDkg(ctx, req.(*DkgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThresholdPlugin_ServiceDesc is the grpc.ServiceDesc for ThresholdPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThresholdPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thresholdapi.ThresholdPlugin",
	HandlerType: (*ThresholdPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoordinateDkg",
			Handler:    _ThresholdPlugin_CoordinateDkg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugins/threshold.proto",
}
