pub mod proto {
    // Plugin module tree is generated by `build.rs` by scanning
    // `proto/plugins/*.proto` for their `package` declarations — one
    // `pub mod <pkg> { tonic::include_proto!("<pkg>"); }` per file.
    pub mod plugins {
        include!(concat!(env!("OUT_DIR"), "/_plugin_modules.rs"));
        // kms.proto uses `package kmsapi;` for its protobuf identity, but
        // gateway code references it as `kms` for ergonomics.
        pub use self::kmsapi as kms;
    }

    pub mod services {
        pub mod ctrng {
            tonic::include_proto!("ctrng");
        }
        pub mod kms {
            tonic::include_proto!("kms");
        }
    }
}

pub mod types;

pub mod logging;
pub mod metrics;

pub mod filters;
pub mod plugins;
pub mod server;
pub mod service_manager;
pub mod services;
pub mod structures;
pub mod trng;
