use crate::common::GatewayError;
use crate::structures::service::ServiceResult;

/// A trait representing a service that can handle service requests.
pub trait ServiceHandler {
    #[allow(async_fn_in_trait)]
    async fn handle(&mut self, svc_req: ServiceRequest) -> Result<ServiceResponse, GatewayError>;
}

/// ServiceRequest is an internal struct that represents a request to a service.
/// The gateway will process http requests by forming the corresponding ServiceRequest
/// object. The ServiceRequest will be sent to the service manager that will route it to the
/// appropriate service.
#[derive(Debug, Clone)]
pub struct ServiceRequest {
    /// The request ID is a unique identifier for the request.
    /// It is generated by the gateway and passed to the service manager.
    /// The service manager will use this ID to track the request and its response.
    pub req_id: u64,
    /// The service to invoke
    pub service: String,
    /// The service provider/s to use.
    pub src: Vec<String>,
    /// Arguments for the service in a vector of [(key, value), ...]
    pub args: Option<Vec<(String, String)>>,
}

/// ServiceResponse is the response from a service.
/// It contains the request ID and the result of the service call.
#[derive(Debug, Clone)]
pub struct ServiceResponse {
    pub req_id: u64,
    pub result: Result<ServiceResult, GatewayError>,
}
