use serde::{Deserialize, Serialize};
use thiserror::Error;

/// A trait representing a service that can handle service requests.
pub trait ServiceHandler {
    #[allow(async_fn_in_trait)]
    async fn handle(&mut self, svc_req: ServiceRequest) -> Result<ServiceResponse, ServiceError>;
}

/// Error type for service interaction
#[derive(Error, Debug, Clone)]
pub enum ServiceError {
    #[error("Internal error: {0}")]
    InternalError(String),
    #[error("Service timeout")]
    ServiceTimeout,
    #[error("Service connection failed: {0}")]
    ServiceConnectionError(String),
    #[error("Service not found: {0}")]
    ServiceNotFoundError(String),
}

/// ServiceRequest is an internal struct that represents a request to a service.
/// The gateway will process http requests by forming the corresponding ServiceRequest
/// object. The ServiceRequest will be sent to the service manager that will route it to the
/// appropriate service.
#[derive(Debug, Clone)]
pub struct ServiceRequest {
    /// The request ID is a unique identifier for the request.
    /// It is generated by the gateway and passed to the service manager.
    /// The service manager will use this ID to track the request and its response.
    pub req_id: u64,
    /// The service to invoke
    pub service: String,
    /// The service provider/s to use.
    pub src: Vec<String>,
    /// Arguments for the service in a vector of [(key, value), ...]
    pub args: Option<Vec<(String, String)>>,
}

/// ServiceResponse is the response from a service.
/// It contains the request ID and the result of the service call.
#[derive(Debug, Clone)]
pub struct ServiceResponse {
    pub req_id: u64,
    pub result: Result<ServiceResult, ServiceError>,
}

/// Signature contains the signature, the public key, and the algorithm used for verification.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Signature {
    /// The signature bytes.
    pub value: String,
    /// The public key used to verify the signature.
    pub pk: String,
    /// The algorithm used for signing (e.g., "ed25519", "rsa", "ecdsa").
    pub algo: String,
}

/// ServiceResult is the result of a service call.
/// It contains the source of the service, the data returned by the service,
/// and the signature of the service.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ServiceResult {
    /// The service that was called.
    pub service: String,
    /// The source of the service.
    /// This is the service provider that provided the data.
    pub src: String,
    /// The data returned by the service.
    pub data: String,
    /// The signature is used to verify the authenticity of the data.
    pub signature: Signature,
}
