name: E2e Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout OpenBao Ethereum plugin
        uses: actions/checkout@v4
        with:
          repository: spacecomputer-io/openbao-eth-plugin-poc
          ref: main
          path: openbao-eth-plugin-poc
          fetch-depth: 1
          token: ${{ secrets.OPENBAO_ETH_PLUGIN_PAT }}
      - name: Checkout OpenBao Threshold plugin
        uses: actions/checkout@v4
        with:
          repository: spacecomputer-io/openbao-threshold-plugin
          ref: main
          path: openbao-threshold-plugin
          fetch-depth: 1
          token: ${{ secrets.OPENBAO_THRESHOLD_PLUGIN_PAT }}
      - name: Build docker images
        run: |
          make docker-build

      - name: Start devenv
        run: |
          make ENV_FILE=.dev.env.ci devenv
        continue-on-error: false

      - name: Run e2e tests
        run: |
          make e2e-all

      - name: Go beacon e2e (happy)
        run: make go-e2e

      - name: Stop devenv
        run: |
          make devenv-down

      - name: Restart devenv (offline)
        run: |
          make ENV_FILE=.dev.env.ci E2E_PROFILE=offline devenv

      - name: Go beacon e2e (offline)
        run: |
          make go-e2e-offline

      - name: Stop devenv
        run: |
          make devenv-down
