name: Test & Build Gateway 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Format
      working-directory: ./gateway
      run: cargo fmt -- --check
    - name: Clippy
      working-directory: ./gateway
      run: cargo clippy -- -D warnings
    - name: Build
      working-directory: ./gateway
      run: cargo build --verbose
    - name: Run unit tests
      working-directory: ./gateway
      run: make test
