name: Rust Vulnerability Scan

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches: [ "*" ]
    # paths:
    #   - '**/Cargo.toml'
    #   - '**/Cargo.lock'
  schedule:
    # Run daily at midnight to catch newly disclosed vulnerabilities
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Run cargo-audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Security audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
