name: TestV0.1 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      working-directory: ./v0.1
      run: make build

    - name: Test
      working-directory: ./v0.1
      run: make test

    - name: Race
      working-directory: ./v0.1
      run: make race

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        working-directory: ./v0.1
